orch:
  image: broadinstitute/firecloud-orchestration:latest
  dns:
    - 172.17.42.1
  ports:
    - "8080:8080"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    GOOGLE_CLIENT_ID: 806222273987-2ntvt4hnfsikqmhhc18l64vheh4cj34q.apps.googleusercontent.com
    AGORA_URL_ROOT: https://agora.dsde-dev.broadinstitute.org
    RAWLS_URL_ROOT: https://rawls.dsde-dev.broadinstitute.org
ui:
  image: broadinstitute/firecloud-ui:latest
  links:
    - orch
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/server.crt:/etc/ssl/certs/server.crt:ro
    - /etc/server.key:/etc/ssl/private/server.key:ro
    - /etc/ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt:ro
  environment:
    GOOGLE_CLIENT_ID: 806222273987-2ntvt4hnfsikqmhhc18l64vheh4cj34q.apps.googleusercontent.com
    LOG_LEVEL: debug
    SERVER_NAME: firecloud.dsde-dev.broadinstitute.org
